
version: '3.5'

services:
    lemmy-ui:

        build:
            context: ./compose
        ports: 
            - "1234:1234"
        volumes:
            - ./:/home/developer
        environment:
            - LEMMY_INTERNAL_HOST=lemmy:8536
            - LEMMY_EXTERNAL_HOST=localhost:8536
            - LEMMY_HTTPS=false
        #command: bash -c "sudo chown -R $USER:$GROUP ~/.npm;sudo chown -R $USER:$GROUP ~/.config;sudo chown $USER:$USER -R .;   yarn install ;sudo npm start;"
        command: bash -c "sudo chown developer:developer -R .;sleep infinity"
        working_dir: /home/developer
        networks:
            - lemmy

    # nginx:
    #     # build:
    #     #     context: ./nginx
    #     image: nginx:alpine
    #     volumes:
    #     # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #     - ./nginx2.conf:/etc/nginx/nginx.conf
    #     ports:
    #         - "1234:1234"
    #     depends_on:
    #         - lemmy-ui
    #     networks:
    #         - lemmy


networks:
      lemmy:
         name: lemmy