
version: '3.5'

services:
    lemmy-ui:
        image: node:latest
        volumes:
            - ./:/lemmy
        command: bash -c "git submodule update --init --recursive; yarn install --pure-lockfile; yarn build:prod; node dist/js/server.js"
        working_dir: /lemmy
        network_mode: host
