
version: '3.5'

services:
    lemmy-ui:
        image: node:latest
        ports: 
            - "7777:7777"
        volumes:
            - ./:/lemmy
        environment:
            - LEMMY_INTERNAL_HOST=lemmy:8536
            - LEMMY_EXTERNAL_HOST=gaybar:1234
            - LEMMY_HTTPS=false
        command: bash -c "git submodule update --init --recursive; yarn install --pure-lockfile; yarn build:prod; node dist/js/server.js"
        working_dir: /lemmy
        networks:
            - lemmy

    nginx:
        build:
            context: ./nginx
        ports:
            - "1234:1234"
        depends_on:
            - lemmy-ui
        networks:
            - lemmy


networks:
      lemmy:
         name: lemmy